name: magnetic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint code
        run: |
          pip install flake8
          flake8 src/  # Replace with your code directory

      - name: Run tests
        run: |
          if [ -f tests/test_main.py ]; then python -m unittest discover -s tests; fi

      - name: Build results
        run: |
          python scripts/generate_results.py
          
